owner: redoper1
repo: upptime-status-page

sites:
  - name: Private website
    url: https://davidrychly.cz/
  - name: Blog
    url: https://blog.davidrychly.cz/
  - name: VPS
    url: https://vps.davidrychly.cz/
  - name: Htmlmage
    url: https://htmlmage.davidrychly.cz/
  - name: Imagemin
    url: https://imagemin.davidrychly.cz/

status-website:
  cname: status.davidrychly.cz
  logoUrl: https://davidrychly.cz/favicon/favicon.svg
  name: Status - David Rychlý
  introTitle: "**Services status**"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://davidrychly.cz
    - title: GitHub repo
      href: https://github.com/$OWNER/$REPO
  theme: dark
