# Change these first
owner: redoper1 # Your GitHub organization or username, where this repository lives
repo: upptime-status-page # The name of this repository

sites:
  - name: Private website
    url: https://davidrychly.cz/
  - name: Blog
    url: https://blog.davidrychly.cz/
  - name: VPS
    url: https://vps.davidrychly.cz/

status-website:
  cname: status.davidrychly.cz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - David Rychlý
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
