owner: redoper1
repo: upptime-status-page

sites:
  - name: Private website
    url: https://davidrychly.cz/
  - name: Blog
    url: https://blog.davidrychly.cz/
  - name: VPS
    url: https://vps.davidrychly.cz/
  - name: Htmlmage API
    url: https://htmlmage.davidrychly.cz/
  - name: Imagemin API
    url: https://imagemin.davidrychly.cz/
  - name: Geoip API
    url: https://geoip.davidrychly.cz/
  - name: Speedtest
    url: https://speedtest.davidrychly.cz/
  - name: Jitsi
    url: https://jitsi.davidrychly.cz/
  - name: Activities tracking app
    url: https://activities-tracking-app.davidrychly.cz/login
  - name: Version check API
    url: https://version-check.davidrychly.cz/
    
assignees:
  - redoper1

status-website:
  cname: status.davidrychly.cz
  logoUrl: https://davidrychly.cz/favicon/favicon.svg
  name: Status - David Rychlý
  introTitle: "**Services status**"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://davidrychly.cz
    - title: GitHub repo
      href: https://github.com/$OWNER/$REPO
  theme: dark
