owner: redoper1
repo: upptime-status-page

sites:
  - name: Personal website
    url: https://www.davidrychly.cz/
  - name: Blog
    url: https://blog.davidrychly.cz/
  - name: Docs
    url: https://docs.davidrychly.cz/
  - name: VPS
    url: https://vps.davidrychly.cz/
  - name: Htmlmage API
    url: https://htmlmage.davidrychly.cz/
  - name: Imagemin API
    url: https://imagemin.davidrychly.cz/
  #- name: Geoip API
  #  url: https://geoip.davidrychly.cz/
  - name: Speedtest
    url: https://speedtest.davidrychly.cz/
  - name: Jitsi
    url: https://jitsi.davidrychly.cz/
  - name: Activities tracking app
    url: https://activities-tracking-app.davidrychly.cz/login
  - name: Version check API
    url: https://version-check.davidrychly.cz/
  - name: Status
    url: https://status.davidrychly.cz/
    
assignees:
  - redoper1

status-website:
  cname: status.davidrychly.cz
  logoUrl: https://davidrychly.cz/favicon/favicon.svg
  name: Status - David Rychlý
  introTitle: "**Services status**"
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://davidrychly.cz
    - title: GitHub repo
      href: https://github.com/$OWNER/$REPO
  theme: dark
  

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  #uptime: "*/5 * * * *"
  uptime: "*/10 * * * *"
